travis:
  secure:
    BINSTAR_TOKEN: r6N32C3A+6PnmiYxc9vSgy9vSA1RxPLzEYXPeHYD3NqEGV3PvxvuDOH++ayzQi1Zg93NlLOnJDEq/6YFocTfpTEymSfRoU89OYujt5mtjqO8odEYJC/WIR4d4qNzVsE5hTGF88RILxIXknLx2YASmhnWCK2zAVqIbn2k9351Vfnxx9qVPZAK4ZajvkbkZbRPImbfW1TbAhNUdy4O7V19WXeB7XvT39UnejJ4XCBS0nPlO9j7E2ub/nTlgZEDah/sTrEEg8ZME0Gnbl6/8zhwgZIt0ZdoBhNoXSNpt3NwSotcPuzDOBqvlFBkX1TxUHR2GrjV9JhtVxqxaCQaMoVRlC6Z0xti0MwfBVi2HlwgATluRO9BpKS160xLXNVCGfvmxbyu5cnbUTT4itRL20qm18GA32K1n9IXZYfzJq+642tdyfpb+JtzSbuhphCf1bqUC0yds4tvy8+ZbjJLvNU+jMbrlTZ9wp8mKHruSLMbG+QpjyrbiWryLp6NZFCQIld3MmeY54+HOAh2KC2GP4HqnQNFCqaellM7+NsdXgE+Nt3U9p9K7Roipe1DDh1AtDSQ0FmpPil2+3qfFa1QbC/STKrzI1kbwFA0t3XF4wY/K+o5z+wtlBISX54HMvGXu1d9pV39rvoQDND08I0GyLPB7fkc+6362bTN2dOgob6h+/w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
